// <auto-generated />
using System;
using Domains.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_commerce.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240310164742_addActive")]
    partial class addActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_commerce.Model.TbCatagery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TbCatageries");
                });

            modelBuilder.Entity("E_commerce.Model.TbColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TbProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TbProductId");

                    b.ToTable("TbColors");
                });

            modelBuilder.Entity("E_commerce.Model.TbProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TbCatageryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TbCatageryId");

                    b.ToTable("TbProducts");
                });

            modelBuilder.Entity("E_commerce.Model.TbSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TbProductId")
                        .HasColumnType("int");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TbProductId");

                    b.ToTable("TbSizes");
                });

            modelBuilder.Entity("E_commerce.Model.TbColor", b =>
                {
                    b.HasOne("E_commerce.Model.TbProduct", null)
                        .WithMany("Colors")
                        .HasForeignKey("TbProductId");
                });

            modelBuilder.Entity("E_commerce.Model.TbProduct", b =>
                {
                    b.HasOne("E_commerce.Model.TbCatagery", null)
                        .WithMany("Products")
                        .HasForeignKey("TbCatageryId");
                });

            modelBuilder.Entity("E_commerce.Model.TbSize", b =>
                {
                    b.HasOne("E_commerce.Model.TbProduct", null)
                        .WithMany("Sizes")
                        .HasForeignKey("TbProductId");
                });

            modelBuilder.Entity("E_commerce.Model.TbCatagery", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_commerce.Model.TbProduct", b =>
                {
                    b.Navigation("Colors");

                    b.Navigation("Sizes");
                });
#pragma warning restore 612, 618
        }
    }
}
